// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonOne: typeof import('./src/components/Global/ButtonOne.vue')['default']
    ButtonTwo: typeof import('./src/components/Global/ButtonTwo.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}

export { }
